# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='m_img',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
