# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_member_m_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='m_img',
        ),
        migrations.AddField(
            model_name='member',
            name='img',
            field=models.ImageField(default='', upload_to='upload/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
