# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 22:43
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170131_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(upload_to=courses.models.UploadToPathAndRename('/home/ayman/Desktop/CSGEEKs_Courses/courses/media/upload')),
        ),
    ]
