# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170131_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
