# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20170131_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=400)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('by', models.CharField(default='', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Video'),
        ),
    ]
