# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='files/')),
                ('date', models.DateField(auto_now_add=True)),
                ('assgin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Assignment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Member')),
            ],
        ),
    ]
