# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='assgin',
            new_name='assign',
        ),
    ]
