# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:28
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20170202_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(upload_to=courses.models.UploadToPathAndRename('/home/ahmmkh/Desktop/project_my_version/CSGEEKs_Courses/courses/media/upload')),
        ),
    ]
